version: '3.7'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  postgres:
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: crud_task_db
      POSTGRES_USER: debug
      POSTGRES_PASSWORD: debug
    image: postgres:12.8
    container_name: postgres_test_crud
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z

  django-runserver:
    restart: always
    build:
      context: .
      dockerfile: ./dockerfiles/django/Dockerfile
    depends_on:
      - postgres
    container_name: django_test_crud
    profiles:
      - runserver
    volumes:
      - .:/app:z
    ports:
      - "8000:8000"
    command: /start

  django-autotests:
    build:
      context: .
      dockerfile: ./dockerfiles/django/Dockerfile
    depends_on:
      - postgres
    container_name: django_test_crud_autotesting
    volumes:
      - .:/app:z
    ports:
      - "8001:8001"
    profiles:
      - test
    command: /start-tests
